-- Disable RLS for public prototype access
ALTER TABLE recruiters DISABLE ROW LEVEL SECURITY;
ALTER TABLE candidates DISABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_experience DISABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_scores DISABLE ROW LEVEL SECURITY;
ALTER TABLE shortlists DISABLE ROW LEVEL SECURITY;
ALTER TABLE shortlist_candidates DISABLE ROW LEVEL SECURITY;
